In [7]:
import binascii
import struct
from PIL import Image
import numpy as np
import scipy
import scipy.misc
import scipy.cluster
import heapq

NUM_CLUSTERS = 5

print('reading image')
im = Image.open('scarf-10539009.jpg')
im = im.resize((150, 150))      # optional, to reduce time
ar = np.asarray(im)
shape = ar.shape
ar = ar.reshape(scipy.product(shape[:2]), shape[2]).astype(float)

print('finding clusters')
codes, dist = scipy.cluster.vq.kmeans(ar, NUM_CLUSTERS)
print('cluster centres:\n', codes)

vecs, dist = scipy.cluster.vq.vq(ar, codes)         # assign codes
counts, bins = scipy.histogram(vecs, len(codes))    # count occurrences

print("countsssss",counts)
index_max = scipy.argmax(counts)

print("index_max",index_max)

# counts.sort()
print("counts",counts,"codes",codes)
# peak=counts[-2]                    # find most frequent

rank=heapq.nlargest(2, range(len(counts)), key=counts.__getitem__)
print("rank",rank)
peak = codes[rank[-1]]
print("peak",peak)
colour = binascii.hexlify(bytearray(int(c) for c in peak)).decode('ascii')
print('most frequent is %s (#%s)' % (peak, colour))


reading image
finding clusters
cluster centres:
 [[ 28.32753263 183.22622747 101.95587321]
 [  7.15377429 145.35257848  72.31894619]
 [135.92871287 226.2950495  180.12475248]
 [254.2688306  254.81814185 254.56447831]
 [  4.41991342 103.67027417  50.16089466]]
countsssss [ 1459  5462   508 13664  1407]
index_max 3
counts [ 1459  5462   508 13664  1407] codes [[ 28.32753263 183.22622747 101.95587321]
 [  7.15377429 145.35257848  72.31894619]
 [135.92871287 226.2950495  180.12475248]
 [254.2688306  254.81814185 254.56447831]
 [  4.41991342 103.67027417  50.16089466]]
rank [3, 1]
peak [  7.15377429 145.35257848  72.31894619]
most frequent is [  7.15377429 145.35257848  72.31894619] (#079148)


C:\Users\Cheta\AppData\Local\Temp\ipykernel_15620\59198480.py:17: DeprecationWarning: scipy.product is deprecated and will be removed in SciPy 2.0.0, use numpy.product instead
  ar = ar.reshape(scipy.product(shape[:2]), shape[2]).astype(float)
C:\Users\Cheta\AppData\Local\Temp\ipykernel_15620\59198480.py:24: DeprecationWarning: scipy.histogram is deprecated and will be removed in SciPy 2.0.0, use numpy.histogram instead
  counts, bins = scipy.histogram(vecs, len(codes))    # count occurrences
C:\Users\Cheta\AppData\Local\Temp\ipykernel_15620\59198480.py:27: DeprecationWarning: scipy.argmax is deprecated and will be removed in SciPy 2.0.0, use numpy.argmax instead
  index_max = scipy.argmax(counts)


# Falabella Assignment

## Extract and identify the colour of scarf


### Pseudocode

1. Train an YOLO model to specifically identify the scarf in an image.
2. Extract the scarf from the input image using YOLO
3. Using scipy count frequency of color in image make 5 clusters
4. take the 2 most abundent cluster, (1 is dropped for background color)
5. package in form of a streamlit application
6. containarize the application: Create Dockerfile
7. create cloudbuild.yml
8. link github with gcp (In marketplace link repo to GCP)
9. Authenticate and setup
10. In Cloud build add a trigger: 
comit changes and deploy to GCP.


![Deployment Flowchart](flowchart.drawio.png)

**Flowchart**

cloudbuild.yml holds all the steps for deployment of the app onto GCP:
1. build the image using Dockerfile in scarf dir.
2. Push Docker image to GCR: google container registry
3. Build image
4. deploy using GKE: k8 files are stored in k8s folder.


